# 公共配置
spring:
 profiles:
# 激活哪一个环境的配置文件
  active: dev

---
# 开发环境
spring:
 profiles: dev
 schedule: 
    # 每隔一分钟执行一次定时任务
    cron1: 0 0/1 * * * ?
    # 每隔两小时执行一次定时任务
    cron2: 0 0 */2 * * ?
 redis:
  database: 0
  host: 127.0.0.1
  port: 6379
  password: 
  timeout: 0
  pool:
   # 最大空闲连接数(默认为8, 负数表示无限)
   max-idle: 8
   # 最小空闲连接数(默认为0, 该值只有为正数才有作用)
   min-idle: 0
   # 连接池最大连接数(使用负值表示没有限制)
   max-active: 8
   # 连接池最大阻塞等待时间(使用负值表示没有限制)
   max-wait: -1
  # Redis缓存时间, 单位: 秒
  default_cache_time: 100
  short_cache_time: 300
  long_cache_time: 1800

---
# 生产环境
spring:
 profiles: pro
 schedule: 
    # 每隔一分钟执行一次定时任务
    cron1: 0 0/1 * * * ?
    # 每隔两小时执行一次定时任务
    cron2: 0 0 */2 * * ?
 redis:
  database: 0
  host: 127.0.0.1
  port: 6379
  password: 
  timeout: 0
  pool:
   # 最大空闲连接数(默认为8, 负数表示无限)
   max-idle: 8
   # 最小空闲连接数(默认为0, 该值只有为正数才有作用)
   min-idle: 0
   # 连接池最大连接数(使用负值表示没有限制)
   max-active: 8
   # 连接池最大阻塞等待时间(使用负值表示没有限制)
   max-wait: -1
  # Redis缓存时间, 单位: 秒
  default_cache_time: 100
  short_cache_time: 300
  long_cache_time: 1800
