# 公共配置
spring:
 profiles:
# 激活哪一个环境的配置文件
  active: dev

---
# 开发环境
spring:
 profiles: dev
 schedule: 
    # 每隔一分钟执行一次定时任务
    cron1: 0 0/1 * * * ?
    # 每隔两小时执行一次定时任务
    cron2: 0 0 */2 * * ?
 redis:
  database: 0
  host: 127.0.0.1
  port: 6379
  password: 
  # 默认缓存时间, 单位, 秒
  default_cache_time: 100
  short_cache_time: 300
  long_cache_time: 1800
  pool:
   max-idle: 8
   min-idle: 0
   max-active: 8
   max-wait: -1

---
# 生产环境
spring:
 profiles: pro
 schedule: 
    # 每隔一分钟执行一次定时任务
    cron1: 0 0/1 * * * ?
    # 每隔两小时执行一次定时任务
    cron2: 0 0 */2 * * ?
 redis:
  database: 0
  host: 127.0.0.1
  port: 6379
  password: 
  # 默认缓存时间, 单位, 秒
  default_cache_time: 100
  short_cache_time: 300
  long_cache_time: 1800
  pool:
   max-idle: 8
   min-idle: 0
   max-active: 8
   max-wait: -1